"""The operation catalog: every operation in every Ads API spec Amazon publishes.

Generated by ``scripts/generate_catalog.py`` from Amazon's OpenAPI specs. Each entry
records the HTTP method, path template, parameters and the vendor media types Amazon
expects, which is what :meth:`ProfileClient.call` needs to send any operation correctly.

Look operations up by full id (``"sponsored-products:ListSponsoredProductsKeywords"``), by
bare operation id when it is unique across APIs, or search with :func:`search`.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import cache
from importlib import resources
from typing import Any


@dataclass(frozen=True)
class Operation:
    id: str
    api: str
    operation_id: str
    method: str
    path: str
    summary: str
    tags: tuple[str, ...]
    deprecated: bool
    path_params: tuple[str, ...]
    query: tuple[dict[str, Any], ...]
    headers: tuple[dict[str, Any], ...]
    content_type: str | None
    accept: str | None
    content_types: tuple[str, ...]
    accepts: tuple[str, ...]
    has_body: bool

    @property
    def read_only(self) -> bool:
        """True for operations that change nothing: GETs, and POSTs whose path or id
        says they list, query or recommend. Used by the MCP server's read-only mode."""
        if self.method == "GET":
            return True
        if self.method != "POST":
            return False
        path = self.path.rstrip("/").lower()
        op = self.operation_id.lower()
        read_words = ("list", "query", "recommendation", "search", "get", "describe", "history")
        return path.endswith(("/list", "/query", "/history")) or any(
            op.startswith(w) or w in path.rsplit("/", 1)[-1] for w in read_words
        )

    def format_path(self, path_params: dict[str, Any] | None = None) -> str:
        params = path_params or {}
        missing = [p for p in self.path_params if p not in params]
        if missing:
            raise ValueError(f"{self.id} needs path parameters: {', '.join(missing)}")
        path = self.path
        for name, value in params.items():
            path = path.replace("{" + name + "}", str(value))
        return path


@dataclass(frozen=True)
class Api:
    slug: str
    title: str
    version: str
    source: str
    section: str | None


@cache
def _load() -> tuple[dict[str, Api], dict[str, Operation]]:
    raw = resources.files("amazon_ads._generated").joinpath("catalog.json").read_text()
    data = json.loads(raw)
    apis = {slug: Api(slug=slug, **info) for slug, info in data["apis"].items()}
    ops: dict[str, Operation] = {}
    for entry in data["operations"]:
        ops[entry["id"]] = Operation(
            id=entry["id"],
            api=entry["api"],
            operation_id=entry["operation_id"],
            method=entry["method"],
            path=entry["path"],
            summary=entry["summary"],
            tags=tuple(entry["tags"]),
            deprecated=entry["deprecated"],
            path_params=tuple(entry["path_params"]),
            query=tuple(entry["query"]),
            headers=tuple(entry["headers"]),
            content_type=entry["content_type"],
            accept=entry["accept"],
            content_types=tuple(entry["content_types"]),
            accepts=tuple(entry["accepts"]),
            has_body=entry["has_body"],
        )
    return apis, ops


def apis() -> dict[str, Api]:
    return dict(_load()[0])


def operations(api: str | None = None) -> list[Operation]:
    ops = _load()[1].values()
    return [op for op in ops if api is None or op.api == api]


def get(operation: str) -> Operation:
    """Find an operation by ``"api:operationId"``, or by bare operation id if unique."""
    ops = _load()[1]
    if operation in ops:
        return ops[operation]
    matches = [op for op in ops.values() if op.operation_id == operation]
    if len(matches) == 1:
        return matches[0]
    if matches:
        ids = ", ".join(op.id for op in matches)
        raise KeyError(f"{operation!r} is ambiguous; use one of: {ids}")
    raise KeyError(f"No operation {operation!r}. Try amazon_ads.catalog.search().")


def search(text: str, *, api: str | None = None, limit: int = 25) -> list[Operation]:
    """Operations whose id, path, summary or tags contain every word of ``text``."""
    words = text.lower().split()
    found = []
    for op in operations(api):
        haystack = " ".join([op.id, op.path, op.summary, *op.tags]).lower()
        if all(w in haystack for w in words):
            found.append(op)
    found.sort(key=lambda op: (op.deprecated, op.api, op.path))
    return found[:limit]
